package com.marteksolution.cooccurrence.database.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import lombok.Data;

/**
 * Language generated by hbm2java
 */
@Entity
@Data
public class Language implements Serializable {

	private static final long serialVersionUID = -6587942443667150567L;
	
	@Id 
	@GeneratedValue
	private Short id;
	
	@Column(name="description", length=15, nullable=false)
	private String description;
}
