package com.marteksolution.cooccurrence.database.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import lombok.Data;

/**
 * Occurrence generated by hbm2java
 */
@Entity
@Data
public class Occurrence implements Serializable {

	private static final long serialVersionUID = -117369375366737698L;

	@Id
	@GeneratedValue
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "word1Id")
	private Word wordByWord1id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "word2Id")
	private Word wordByWord2id;

	@Column(name = "score")
	private int score;

	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinColumn(name="occurrenceId")
	private Set<SentenceOccurrence> sentenceOccurrences = new HashSet<SentenceOccurrence>();

}
