package com.marteksolution.cooccurrence.database.entity;

import java.io.Serializable;

import javax.persistence.Embeddable;

import lombok.Data;

/**
 * SentenceoccurrenceId generated by hbm2java
 */
@Embeddable
@Data
public class SentenceOccurrenceId implements Serializable {

	private static final long serialVersionUID = 2865037060570411045L;

	private int sentenceId;
	private int occurenceId;
}
