package com.marteksolution.cooccurrence.database.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import lombok.Data;

/**
 * Unknownword generated by hbm2java
 */
@Entity
@Data
public class UnknownWord implements Serializable {

	private static final long serialVersionUID = -4196121135506443373L;
	
	@Id 
	@GeneratedValue
	private Integer id;
	
	@Column(name = "description", length = 45, nullable = false)
	private String description;

}
