package com.marteksolution.cooccurrence.database.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import lombok.Data;

/**
 * Word generated by hbm2java
 */
@Entity
@Data
public class Word implements Serializable {

	private static final long serialVersionUID = 3844460051047468077L;
	
	@Id 
	@GeneratedValue
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "languageId")
	private Language language;
	
	@Column(name="description", length=63, nullable=false)
	private String description;
	
	@Column(name="ignored")
	private boolean ignored;
	
	@Column(name="weak")
	private boolean weak;
	
	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinColumn(name="wordId")
	private Set<Definition> definitions = new HashSet<Definition>();
	
	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinColumn(name="wordId")
	private Set<WordVariation> wordvariations = new HashSet<WordVariation>();
	
	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinColumn(name="wordId")
	private Set<Type> types = new HashSet<Type>();

}
